### ISSUE TITLE
usage of marc relator terms

### ISSUE THREAD

**Issue by schassan** [msDesc/consolidated-tei-schema#37]
Hi, 

I have to report two issues, that are mere typos and/or need adjustment:

In `<div xml:id="personalnames">` you give the address of the relators list. Within that you use a double slash. Although browsers can cope with that you might want to correct this to a single slash?

You describe that and how the relator codes shall be used and in the connected example you don't do it yourself:

```
<egXML xmlns="http://www.tei-c.org/ns/Examples">
  Common-place book of
  <persName role="scribe formerOwner" key="person_697">John Curteys</persName> 
  of Winchester College and New College, Oxford
</egXML>
```

Shouldn't that read `<persName role="scr fmo" key="person_697">` ?

**Comment by schassan** [comment]
I recognise that the latter "problem" occurs in other places of the ODD too:

```
<provenance resp="#DL">Purchased from Thorpe by 
<persName key="person_69848690" 
  role="formerOwner">Douce</persName>, 
Feb. 1833.</provenance>
```

**Comment by holfordm** [comment]
Thanks for reporting these inconsistencies @schassan . They've been fixed in the latest release - the HTML has been updated as well (https://msdesc.github.io/consolidated-tei-schema/msdesc.html)

**Comment by holfordm** [comment]
I'll correct the issue with the double slash as well...
